import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Luciela</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div className={styles.sectionOne}>
          <img
            src='/HomePrincipal.png'
            alt='Descripción de la imagen'
            className={styles.imageContainer}
            style={{
              width: '100%',
              height: 'auto', // Para mantener la relación de aspecto, usa 'height: auto'
              objectFit: 'cover', // Ajusta la imagen para cubrir el contenedor sin deformarla
            }}
          />
          <Header />
          <div className={styles.title}>
            <p>
              Lo sostenible
              <br /> puede ser
              <br /> bello
            </p>
            <div className={styles.dots}>
              <div className={styles.dot}></div>
              <div className={styles.dot}></div>
              <div className={styles.dot}></div>
              <div className={styles.dot}></div>
              <div className={styles.dot}></div>
            </div>
          </div>

          <img src='/fastforward.svg' className={styles.botonmovimiento} />
        </div>
        <div className={styles.sectionTwo}>
          <h1>SectionTwo</h1>
        </div>
        <div className={styles.sectionThree}>
          <h1>SectionThree</h1>
        </div>
        <div className={styles.sectionFour}>
          <h1>SectionFour</h1>
        </div>
        <div className={styles.sectionFive}>
          <h1>SectionFive</h1>
        </div>
      </main>
    </>
  );
}
